name: rust_ci

on:
#  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
      - name: setup package
        run: sudo apt install libparted-dev  
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
