name: rust_ci

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup package
        run: sudo apt install libparted-dev  
      - name: install toolchain
        run: |
          rustup install stable
          rustup default stable
      - name: build
        run: cargo test
      - name: test
        run: cargo test
